from datetime import datetime
from typing import Any, Optional

from sqlalchemy import Index, PrimaryKeyConstraint, String, text
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import Mapped, mapped_column

from backend.src.database.orm.base import Base
from backend.src.database.orm.models.legacy import MYSQL_TABLE_OPTIONS


class RoomBaseModel(Base):
  __tablename__ = "room_base"
  __table_args__ = (
    PrimaryKeyConstraint('now', 'id', 'start_time'),
    Index("idx_room_base_id_start_time", 'id', 'start_time'),
    dict(MYSQL_TABLE_OPTIONS),
  )

  now: Mapped[datetime] = mapped_column(mysql.TIMESTAMP(fsp=3), nullable=False)
  id: Mapped[str] = mapped_column(String(200), nullable=False)
  id_str: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
  title: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  introduction: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  share_url: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  user_share_text: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  anchor_share_text: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  create_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  start_time: Mapped[int] = mapped_column(mysql.BIGINT(unsigned=False), nullable=False)
  finish_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  stream_close_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  finish_reason: Mapped[Optional[int]] = mapped_column(mysql.SMALLINT(unsigned=True), nullable=True)
  acquaintance_status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  owner_user_id: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  app_id: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  base_category: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  category: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  client_version: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  orientation: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  layout: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  room_layout: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  room_tag: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  live_room_mode: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  live_platform_source: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  cell_style: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  os_type: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  owner_device_id: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  owner_open_id: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
  visibility_range: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  webcast_sdk_version: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
  stream_id: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  stream_id_str: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
  live_id: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  stream_provider: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  like_count: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  user_count: Mapped[Optional[int]] = mapped_column(mysql.INTEGER(unsigned=True), nullable=True, server_default=text("0"))
  popularity: Mapped[Optional[int]] = mapped_column(mysql.INTEGER(unsigned=True), nullable=True, server_default=text("0"))
  danmaku_detail: Mapped[Optional[int]] = mapped_column(mysql.INTEGER(unsigned=True), nullable=True, server_default=text("0"))
  web_count: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  webcast_comment_tcs: Mapped[Optional[int]] = mapped_column(mysql.INTEGER(unsigned=True), nullable=True, server_default=text("0"))
  gift_msg_style: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  share_msg_style: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  follow_msg_style: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  fansclub_msg_style: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  sell_goods: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  has_commerce_goods: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  is_replay: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  replay: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  highlight: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  use_filter: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  title_recommend: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  enable_room_perspective: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  with_aggregate_column: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  with_draw_something: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  with_ktv: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  with_linkmic: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_normal: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_audio: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_linkmic: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_official: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_sandbox: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_screenshot: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_third_party: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_vs_live: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  live_type_vs_premiere: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  linkmic_layout: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  auth_city: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  location: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  distance: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  distance_city: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  distance_km: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  real_distance: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  dynamic_cover_uri: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  vertical_cover_uri: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  finish_url: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  forum_extra_data: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  private_info: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  item_explicit_info: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  hot_sentence_info: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  relation_tag: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  stamps: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  room_create_ab_param: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  scroll_config: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  mosaic_tip: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  popularity_str: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
  preview_copy: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  wait_copy: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  short_title: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  video_feed_tag: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  screen_capture_sharing_title: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  common_label_list: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  content_tag: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  challenge_info: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  anchor_scheduled_time_text: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  anchor_tab_type: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  comment_name_mode: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  fcdn_appid: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  game_room_type: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  official_channel_open_id: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
  official_channel_uid: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  search_id: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  group_id: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  group_source: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  sofa_layout: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  sun_daily_icon_content: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  ranklist_audience_type: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  redpacket_audience_auth: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  toutiao_cover_recommend_level: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  toutiao_title_recommend_level: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  preview_flow_tag: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  replay_location: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  room_audit_status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  mosaic_status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  lottery_finish_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  luckymoney_num: Mapped[Optional[int]] = mapped_column(mysql.INTEGER(unsigned=True), nullable=True, server_default=text("0"))
  has_promotion_games: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  is_need_check_list: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  is_official_channel_room: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  is_show_inquiry_ball: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  is_show_user_card_switch: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  auto_cover: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  business_live: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  book_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  book_end_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  linkmic_display_type: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  vid: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
  vs_main_replay_id: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
  last_ping_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  pre_enter_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True)
  city_top_distance: Mapped[Optional[str]] = mapped_column(mysql.TINYTEXT(), nullable=True)
  cover: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  content_label: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  feed_room_label: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  guide_button: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  comment_box: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  link_mic: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  living_room_attrs: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  pack_meta: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  paid_live_data: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  room_view_stats: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  extra: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  room_auth: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  short_touch_area_config: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  stream_url: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  stats: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  owner: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  official_channel: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  admin_user_ids: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  admin_user_open_ids: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  deco_list: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  fans_group_admin_user_ids: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  fans_group_admin_user_open_ids: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  filter_words: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  live_distribution: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  sharing_music_id_list: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  tags: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  top_fans: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  upper_right_widget_data_list: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  vs_roles: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  room_tabs: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  assist_label_list: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  AnchorABMap: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  linker_map: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  dynamic_cover_dict: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  created_at: Mapped[Optional[datetime]] = mapped_column(mysql.TIMESTAMP(), nullable=True, server_default=text("CURRENT_TIMESTAMP"))
  updated_at: Mapped[Optional[datetime]] = mapped_column(mysql.TIMESTAMP(), nullable=True, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
