from datetime import datetime
from typing import Any, Optional

from sqlalchemy import Index, PrimaryKeyConstraint, String, text
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import Mapped, mapped_column

from backend.src.database.orm.base import Base
from backend.src.database.orm.models.legacy import MYSQL_TABLE_OPTIONS


class UserModel(Base):
  __tablename__ = "user"
  __table_args__ = (
    PrimaryKeyConstraint('id'),
    dict(MYSQL_TABLE_OPTIONS, comment="用户信息表"),
  )

  id: Mapped[str] = mapped_column(String(200), nullable=False)
  adversary_authorization_info: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  adversary_user_status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  age_range: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  allow_be_located: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_find_by_contacts: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_others_download_video: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_others_download_when_sharing_video: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_share_show_profile: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_show_in_gossip: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_show_my_action: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_strange_comment: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_unfollower_comment: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  allow_use_linkmic: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  authorization_info: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  badge_image_list: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  badge_image_list_v2: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  bg_img_url: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  birthday: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  birthday_description: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  birthday_valid: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  block_status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  city: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  comment_restrict: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  commerce_webcast_config_ids: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  constellation: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
  consume_diamond_level: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  create_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  desensitized_nickname: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
  disable_ichat: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  display_id: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
  enable_ichat_img: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  exp: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  experience: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  fan_ticket_count: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  fold_stranger_chat: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  follow_status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  foreign_user: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  gender: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  hotsoon_verified: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  hotsoon_verified_reason: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
  ichat_restrict_type: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  income_share_percent: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  is_anonymous: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  is_follower: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  is_following: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  level: Mapped[Optional[int]] = mapped_column(mysql.SMALLINT(unsigned=True), nullable=True, server_default=text("0"))
  link_mic_stats: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  location_city: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  media_badge_image_list: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  modify_time: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  mystery_man: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  need_profile_guide: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  new_real_time_icons: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  nickname: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
  pay_score: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  pay_scores: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  public_area_oper_freq: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  push_comment_status: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  push_digg: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  push_follow: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  push_friend_action: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  push_ichat: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  push_status: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  push_video_post: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  push_video_recommend: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  real_time_icons: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  remark_name: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
  sec_uid: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  secret: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  share_qrcode_uri: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  short_id: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
  signature: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  special_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  status: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  telephone: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
  ticket_count: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  top_fans: Mapped[Optional[Any]] = mapped_column(mysql.JSON(), nullable=True)
  top_vip_no: Mapped[Optional[int]] = mapped_column(mysql.INTEGER(unsigned=True), nullable=True, server_default=text("0"))
  total_recharge_diamond_count: Mapped[Optional[int]] = mapped_column(mysql.BIGINT(unsigned=False), nullable=True, server_default=text("0"))
  user_canceled: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  user_open_id: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
  user_role: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  verified: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  verified_content: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  verified_mobile: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  verified_reason: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
  watch_duration_month: Mapped[Optional[int]] = mapped_column(mysql.INTEGER(unsigned=True), nullable=True, server_default=text("0"))
  web_rid: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
  webcast_uid: Mapped[Optional[str]] = mapped_column(mysql.TEXT(), nullable=True)
  with_car_management_permission: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  with_commerce_permission: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  with_fusion_shop_entry: Mapped[Optional[bool]] = mapped_column(mysql.TINYINT(unsigned=False), nullable=True, server_default=text("0"))
  can_view_webcast_private: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  webcast_nick: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
  webcast_private: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  hide_by_room: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  link_mask: Mapped[Optional[int]] = mapped_column(mysql.TINYINT(unsigned=True), nullable=True, server_default=text("0"))
  created_at: Mapped[Optional[datetime]] = mapped_column(mysql.TIMESTAMP(), nullable=True, server_default=text("CURRENT_TIMESTAMP"))
  updated_at: Mapped[Optional[datetime]] = mapped_column(mysql.TIMESTAMP(), nullable=True, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
