"""Initial managed schema baseline.

Revision ID: 0001_initial_schema
Revises: None

This immutable revision owns only the 12 managed tables. The downgrade is intended
for disposable development databases; it never discovers or drops unmanaged tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('fans_group_admin_user_id',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('index', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('fans_group_admin_user_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('index', 'platform', 'room_id', name=op.f('pk_fans_group_admin_user_id')),
    sa.UniqueConstraint('platform', 'room_id', 'fans_group_admin_user_id', name='unique_record'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('fans_group_admin_user_open_id',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('index', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('fans_group_admin_user_open_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('index', 'platform', 'room_id', name=op.f('pk_fans_group_admin_user_open_id')),
    sa.UniqueConstraint('platform', 'room_id', 'fans_group_admin_user_open_id', name='unique_record'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('favorite_owner',
    sa.Column('owner_user_id', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('score', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('owner_user_id', 'platform', name=op.f('pk_favorite_owner')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('live_record',
    sa.Column('now', mysql.TIMESTAMP(fsp=3), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('owner_user_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('start_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('finish_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('status_code', mysql.TINYINT(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('now', 'platform', 'owner_user_id', 'room_id', name=op.f('pk_live_record')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('room_admin_user_id',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('index', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('index', 'platform', 'room_id', name=op.f('pk_room_admin_user_id')),
    sa.UniqueConstraint('platform', 'room_id', 'admin_user_id', name='unique_record'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('room_admin_user_open_id',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('index', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('admin_user_open_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('index', 'platform', 'room_id', name=op.f('pk_room_admin_user_open_id')),
    sa.UniqueConstraint('platform', 'room_id', 'admin_user_open_id', name='unique_record'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('room_base',
    sa.Column('now', mysql.TIMESTAMP(fsp=3), nullable=False),
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('id_str', sa.String(length=200), nullable=True),
    sa.Column('title', mysql.TINYTEXT(), nullable=True),
    sa.Column('introduction', mysql.TEXT(), nullable=True),
    sa.Column('share_url', mysql.TEXT(), nullable=True),
    sa.Column('user_share_text', mysql.TEXT(), nullable=True),
    sa.Column('anchor_share_text', mysql.TEXT(), nullable=True),
    sa.Column('create_time', mysql.BIGINT(), nullable=True),
    sa.Column('start_time', mysql.BIGINT(), nullable=False),
    sa.Column('finish_time', mysql.BIGINT(), nullable=True),
    sa.Column('stream_close_time', mysql.BIGINT(), nullable=True),
    sa.Column('status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('finish_reason', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('acquaintance_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('owner_user_id', mysql.BIGINT(), nullable=True),
    sa.Column('app_id', mysql.BIGINT(), nullable=True),
    sa.Column('base_category', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('category', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('client_version', mysql.BIGINT(), nullable=True),
    sa.Column('orientation', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('layout', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('room_layout', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('room_tag', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('live_room_mode', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('live_platform_source', mysql.TINYTEXT(), nullable=True),
    sa.Column('cell_style', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('os_type', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('owner_device_id', mysql.BIGINT(), nullable=True),
    sa.Column('owner_open_id', sa.String(length=200), nullable=True),
    sa.Column('visibility_range', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('webcast_sdk_version', sa.String(length=20), nullable=True),
    sa.Column('stream_id', mysql.BIGINT(), nullable=True),
    sa.Column('stream_id_str', sa.String(length=200), nullable=True),
    sa.Column('live_id', mysql.BIGINT(), nullable=True),
    sa.Column('stream_provider', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('like_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('popularity', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('danmaku_detail', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('web_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('webcast_comment_tcs', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('gift_msg_style', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('share_msg_style', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('follow_msg_style', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('fansclub_msg_style', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('sell_goods', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('has_commerce_goods', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_replay', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('replay', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('highlight', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('use_filter', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('title_recommend', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('enable_room_perspective', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_aggregate_column', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_draw_something', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_ktv', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_linkmic', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_normal', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_audio', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_linkmic', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_official', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_sandbox', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_screenshot', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_third_party', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_vs_live', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('live_type_vs_premiere', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('linkmic_layout', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('auth_city', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('distance', sa.String(length=100), nullable=True),
    sa.Column('distance_city', sa.String(length=100), nullable=True),
    sa.Column('distance_km', sa.String(length=100), nullable=True),
    sa.Column('real_distance', sa.String(length=100), nullable=True),
    sa.Column('dynamic_cover_uri', mysql.TEXT(), nullable=True),
    sa.Column('vertical_cover_uri', mysql.TEXT(), nullable=True),
    sa.Column('finish_url', mysql.TEXT(), nullable=True),
    sa.Column('forum_extra_data', mysql.TEXT(), nullable=True),
    sa.Column('private_info', mysql.TEXT(), nullable=True),
    sa.Column('item_explicit_info', mysql.TEXT(), nullable=True),
    sa.Column('hot_sentence_info', mysql.TEXT(), nullable=True),
    sa.Column('relation_tag', mysql.TINYTEXT(), nullable=True),
    sa.Column('stamps', mysql.TEXT(), nullable=True),
    sa.Column('room_create_ab_param', mysql.TEXT(), nullable=True),
    sa.Column('scroll_config', mysql.TEXT(), nullable=True),
    sa.Column('mosaic_tip', mysql.TINYTEXT(), nullable=True),
    sa.Column('popularity_str', sa.String(length=50), nullable=True),
    sa.Column('preview_copy', mysql.TINYTEXT(), nullable=True),
    sa.Column('wait_copy', mysql.TINYTEXT(), nullable=True),
    sa.Column('short_title', mysql.TINYTEXT(), nullable=True),
    sa.Column('video_feed_tag', mysql.TINYTEXT(), nullable=True),
    sa.Column('screen_capture_sharing_title', mysql.TINYTEXT(), nullable=True),
    sa.Column('common_label_list', mysql.TINYTEXT(), nullable=True),
    sa.Column('content_tag', mysql.TINYTEXT(), nullable=True),
    sa.Column('challenge_info', mysql.TINYTEXT(), nullable=True),
    sa.Column('anchor_scheduled_time_text', mysql.TEXT(), nullable=True),
    sa.Column('anchor_tab_type', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('comment_name_mode', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('fcdn_appid', mysql.BIGINT(), nullable=True),
    sa.Column('game_room_type', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('official_channel_open_id', sa.String(length=200), nullable=True),
    sa.Column('official_channel_uid', mysql.BIGINT(), nullable=True),
    sa.Column('search_id', mysql.BIGINT(), nullable=True),
    sa.Column('group_id', mysql.BIGINT(), nullable=True),
    sa.Column('group_source', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('sofa_layout', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('sun_daily_icon_content', mysql.TINYTEXT(), nullable=True),
    sa.Column('ranklist_audience_type', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('redpacket_audience_auth', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('toutiao_cover_recommend_level', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('toutiao_title_recommend_level', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('preview_flow_tag', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('replay_location', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('room_audit_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('mosaic_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('lottery_finish_time', mysql.BIGINT(), nullable=True),
    sa.Column('luckymoney_num', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('has_promotion_games', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('is_need_check_list', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_official_channel_room', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_show_inquiry_ball', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_show_user_card_switch', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('auto_cover', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('business_live', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('book_time', mysql.BIGINT(), nullable=True),
    sa.Column('book_end_time', mysql.BIGINT(), nullable=True),
    sa.Column('linkmic_display_type', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('vid', sa.String(length=200), nullable=True),
    sa.Column('vs_main_replay_id', sa.String(length=200), nullable=True),
    sa.Column('last_ping_time', mysql.BIGINT(), nullable=True),
    sa.Column('pre_enter_time', mysql.BIGINT(), nullable=True),
    sa.Column('city_top_distance', mysql.TINYTEXT(), nullable=True),
    sa.Column('cover', mysql.JSON(), nullable=True),
    sa.Column('content_label', mysql.JSON(), nullable=True),
    sa.Column('feed_room_label', mysql.JSON(), nullable=True),
    sa.Column('guide_button', mysql.JSON(), nullable=True),
    sa.Column('comment_box', mysql.JSON(), nullable=True),
    sa.Column('link_mic', mysql.JSON(), nullable=True),
    sa.Column('living_room_attrs', mysql.JSON(), nullable=True),
    sa.Column('pack_meta', mysql.JSON(), nullable=True),
    sa.Column('paid_live_data', mysql.JSON(), nullable=True),
    sa.Column('room_view_stats', mysql.JSON(), nullable=True),
    sa.Column('extra', mysql.JSON(), nullable=True),
    sa.Column('room_auth', mysql.JSON(), nullable=True),
    sa.Column('short_touch_area_config', mysql.JSON(), nullable=True),
    sa.Column('stream_url', mysql.JSON(), nullable=True),
    sa.Column('stats', mysql.JSON(), nullable=True),
    sa.Column('owner', mysql.JSON(), nullable=True),
    sa.Column('official_channel', mysql.JSON(), nullable=True),
    sa.Column('admin_user_ids', mysql.JSON(), nullable=True),
    sa.Column('admin_user_open_ids', mysql.JSON(), nullable=True),
    sa.Column('deco_list', mysql.JSON(), nullable=True),
    sa.Column('fans_group_admin_user_ids', mysql.JSON(), nullable=True),
    sa.Column('fans_group_admin_user_open_ids', mysql.JSON(), nullable=True),
    sa.Column('filter_words', mysql.JSON(), nullable=True),
    sa.Column('live_distribution', mysql.JSON(), nullable=True),
    sa.Column('sharing_music_id_list', mysql.JSON(), nullable=True),
    sa.Column('tags', mysql.JSON(), nullable=True),
    sa.Column('top_fans', mysql.JSON(), nullable=True),
    sa.Column('upper_right_widget_data_list', mysql.JSON(), nullable=True),
    sa.Column('vs_roles', mysql.JSON(), nullable=True),
    sa.Column('room_tabs', mysql.JSON(), nullable=True),
    sa.Column('assist_label_list', mysql.JSON(), nullable=True),
    sa.Column('AnchorABMap', mysql.JSON(), nullable=True),
    sa.Column('linker_map', mysql.JSON(), nullable=True),
    sa.Column('dynamic_cover_dict', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('now', 'id', 'start_time', name=op.f('pk_room_base')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_room_base_id_start_time', 'room_base', ['id', 'start_time'], unique=False)
    op.create_table('room_deco',
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('deco_index', mysql.TINYINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('deco_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('deco_type', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('kind', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('audit_text_color', sa.String(length=7), nullable=True),
    sa.Column('content', mysql.TINYTEXT(), nullable=True),
    sa.Column('status', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('text_color', sa.String(length=7), nullable=True),
    sa.Column('text_size', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('position_x', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('position_y', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('width', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('height', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('max_length', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('sub_type', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('text_image_adjustable_start_position', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('text_image_adjustable_end_position', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('input_rect', mysql.JSON(), nullable=True),
    sa.Column('nine_patch_image', mysql.JSON(), nullable=True),
    sa.Column('reservation', mysql.JSON(), nullable=True),
    sa.Column('text_font_config', mysql.JSON(), nullable=True),
    sa.Column('text_special_effects', mysql.JSON(), nullable=True),
    sa.Column('image_data', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('deco_index', 'platform', 'room_id', name=op.f('pk_room_deco')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_deco_type', 'room_deco', ['deco_type'], unique=False)
    op.create_table('room_owner_v2',
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True),
    sa.Column('owner_open_id', sa.String(length=200), nullable=True),
    sa.Column('owner_device_id', mysql.BIGINT(), nullable=True),
    sa.Column('sec_uid', mysql.TEXT(), nullable=True),
    sa.Column('user_open_id', sa.String(length=200), nullable=True),
    sa.Column('short_id', sa.String(length=50), nullable=True),
    sa.Column('display_id', sa.String(length=50), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('signature', mysql.TEXT(), nullable=True),
    sa.Column('share_qrcode_uri', mysql.TEXT(), nullable=True),
    sa.Column('special_id', sa.String(length=100), nullable=True),
    sa.Column('status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('bg_img_url', mysql.TEXT(), nullable=True),
    sa.Column('gender', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('constellation', sa.String(length=20), nullable=True),
    sa.Column('age_range', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('birthday', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('birthday_description', sa.String(length=100), nullable=True),
    sa.Column('birthday_valid', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('foreign_user', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('mystery_man', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('level', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('exp', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('experience', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('fan_ticket_count', mysql.BIGINT(), nullable=True),
    sa.Column('consume_diamond_level', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('income_share_percent', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('link_mic_stats', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('media_badge_image_list', mysql.JSON(), nullable=True),
    sa.Column('modify_time', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('pay_score', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('pay_scores', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('need_profile_guide', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('new_real_time_icons', mysql.JSON(), nullable=True),
    sa.Column('real_time_icons', mysql.JSON(), nullable=True),
    sa.Column('follow_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('is_follower', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_following', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('follow_info', mysql.JSON(), nullable=True),
    sa.Column('is_anonymous', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('hotsoon_verified', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('hotsoon_verified_reason', sa.String(length=255), nullable=True),
    sa.Column('ichat_restrict_type', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('disable_ichat', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('enable_ichat_img', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('fold_stranger_chat', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('desensitized_nickname', sa.String(length=50), nullable=True),
    sa.Column('verified', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('verified_reason', sa.String(length=255), nullable=True),
    sa.Column('verified_content', mysql.TEXT(), nullable=True),
    sa.Column('verified_mobile', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('enterprise_verify_reason', sa.String(length=255), nullable=True),
    sa.Column('custom_verify', sa.String(length=100), nullable=True),
    sa.Column('block_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('comment_restrict', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('public_area_oper_freq', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('push_comment_status', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_digg', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_follow', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_friend_action', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_ichat', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_status', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_video_post', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_video_recommend', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('secret', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('user_role', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('webcast_private', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('can_view_webcast_private', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('user_canceled', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('with_commerce_permission', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_fusion_shop_entry', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_car_management_permission', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('adversary_authorization_info', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('adversary_user_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('authorization_info', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_be_located', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_find_by_contacts', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_others_download_video', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_others_download_when_sharing_video', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_share_show_profile', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_show_in_gossip', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_show_my_action', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_strange_comment', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_unfollower_comment', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_use_linkmic', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('remark_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_large', mysql.JSON(), nullable=True),
    sa.Column('avatar_medium', mysql.JSON(), nullable=True),
    sa.Column('avatar_thumb', mysql.JSON(), nullable=True),
    sa.Column('badge_image_list', mysql.JSON(), nullable=True),
    sa.Column('badge_image_list_v2', mysql.JSON(), nullable=True),
    sa.Column('commerce_webcast_config_ids', mysql.JSON(), nullable=True),
    sa.Column('authentication_info', mysql.JSON(), nullable=True),
    sa.Column('border_data', mysql.JSON(), nullable=True),
    sa.Column('pay_grade_data', mysql.JSON(), nullable=True),
    sa.Column('fans_club_data', mysql.JSON(), nullable=True),
    sa.Column('fans_group_info', mysql.JSON(), nullable=True),
    sa.Column('subscribe_data', mysql.JSON(), nullable=True),
    sa.Column('user_attr_data', mysql.JSON(), nullable=True),
    sa.Column('user_dress_info_data', mysql.JSON(), nullable=True),
    sa.Column('biz_relation_data', mysql.JSON(), nullable=True),
    sa.Column('j_accredit_info_data', mysql.JSON(), nullable=True),
    sa.Column('own_room_data', mysql.JSON(), nullable=True),
    sa.Column('total_recharge_diamond_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('watch_duration_month', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('web_rid', sa.String(length=100), nullable=True),
    sa.Column('webcast_nick', sa.String(length=50), nullable=True),
    sa.Column('webcast_uid', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_room_owner_v2')),
    comment='主播信息表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_nickname', 'room_owner_v2', ['nickname'], unique=False)
    op.create_index('idx_user_id', 'room_owner_v2', ['user_id'], unique=False)
    op.create_table('room_stats',
    sa.Column('now', mysql.TIMESTAMP(fsp=3), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('room_id', sa.String(length=200), nullable=False),
    sa.Column('comment_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('digg_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('dou_plus_promotion', mysql.TINYTEXT(), nullable=True),
    sa.Column('enter_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('fan_ticket', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('follow_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('gift_uv_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('like_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('money', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_user', mysql.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_user_desp', mysql.TEXT(), nullable=True),
    sa.Column('total_user_str', sa.String(length=100), nullable=True),
    sa.Column('up_right_stats_str', sa.String(length=100), nullable=True),
    sa.Column('up_right_stats_str_complete', mysql.TINYTEXT(), nullable=True),
    sa.Column('user_count_str', sa.String(length=100), nullable=True),
    sa.Column('watermelon', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('welfare_donation_amount', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_count_composition_city', mysql.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_count_composition_my_follow', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_count_composition_other', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_count_composition_video_detail', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('now', 'platform', 'room_id', name=op.f('pk_room_stats')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('share_url',
    sa.Column('owner_user_id', sa.String(length=200), nullable=False),
    sa.Column('sec_user_id', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('post_share_url', sa.String(length=100), nullable=True),
    sa.Column('live_share_url', sa.String(length=100), nullable=True),
    sa.Column('directory_name', sa.String(length=100), nullable=True),
    sa.Column('user_status', sa.String(length=100), nullable=True),
    sa.Column('actived_count', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('owner_user_id', name=op.f('pk_share_url')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_nickname', 'share_url', ['nickname'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('adversary_authorization_info', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('adversary_user_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('age_range', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_be_located', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_find_by_contacts', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_others_download_video', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_others_download_when_sharing_video', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_share_show_profile', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_show_in_gossip', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_show_my_action', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_strange_comment', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_unfollower_comment', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('allow_use_linkmic', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('authorization_info', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('badge_image_list', mysql.JSON(), nullable=True),
    sa.Column('badge_image_list_v2', mysql.JSON(), nullable=True),
    sa.Column('bg_img_url', mysql.TEXT(), nullable=True),
    sa.Column('birthday', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('birthday_description', sa.String(length=100), nullable=True),
    sa.Column('birthday_valid', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('block_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('comment_restrict', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('commerce_webcast_config_ids', mysql.JSON(), nullable=True),
    sa.Column('constellation', sa.String(length=20), nullable=True),
    sa.Column('consume_diamond_level', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('create_time', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('desensitized_nickname', sa.String(length=50), nullable=True),
    sa.Column('disable_ichat', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('display_id', sa.String(length=50), nullable=True),
    sa.Column('enable_ichat_img', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('exp', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('experience', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('fan_ticket_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('fold_stranger_chat', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('follow_status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('foreign_user', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('gender', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('hotsoon_verified', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('hotsoon_verified_reason', sa.String(length=255), nullable=True),
    sa.Column('ichat_restrict_type', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('income_share_percent', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('is_anonymous', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_follower', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_following', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('level', mysql.SMALLINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('link_mic_stats', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('media_badge_image_list', mysql.JSON(), nullable=True),
    sa.Column('modify_time', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('mystery_man', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('need_profile_guide', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('new_real_time_icons', mysql.JSON(), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('pay_score', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('pay_scores', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('public_area_oper_freq', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('push_comment_status', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_digg', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_follow', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_friend_action', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_ichat', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_status', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_video_post', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('push_video_recommend', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('real_time_icons', mysql.JSON(), nullable=True),
    sa.Column('remark_name', sa.String(length=50), nullable=True),
    sa.Column('sec_uid', mysql.TEXT(), nullable=True),
    sa.Column('secret', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('share_qrcode_uri', mysql.TEXT(), nullable=True),
    sa.Column('short_id', sa.String(length=50), nullable=True),
    sa.Column('signature', mysql.TEXT(), nullable=True),
    sa.Column('special_id', sa.String(length=100), nullable=True),
    sa.Column('status', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('ticket_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('top_fans', mysql.JSON(), nullable=True),
    sa.Column('top_vip_no', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('total_recharge_diamond_count', mysql.BIGINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_canceled', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('user_open_id', sa.String(length=200), nullable=True),
    sa.Column('user_role', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('verified', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('verified_content', mysql.TEXT(), nullable=True),
    sa.Column('verified_mobile', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('verified_reason', sa.String(length=255), nullable=True),
    sa.Column('watch_duration_month', mysql.INTEGER(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('web_rid', sa.String(length=100), nullable=True),
    sa.Column('webcast_uid', mysql.TEXT(), nullable=True),
    sa.Column('with_car_management_permission', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_commerce_permission', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('with_fusion_shop_entry', mysql.TINYINT(), server_default=sa.text('0'), nullable=True),
    sa.Column('can_view_webcast_private', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('webcast_nick', sa.String(length=50), nullable=True),
    sa.Column('webcast_private', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('hide_by_room', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('link_mask', mysql.TINYINT(unsigned=True), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    comment='用户信息表',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )


def downgrade() -> None:
    op.drop_table('user')
    op.drop_table('share_url')
    op.drop_table('room_stats')
    op.drop_table('room_owner_v2')
    op.drop_table('room_deco')
    op.drop_table('room_base')
    op.drop_table('room_admin_user_open_id')
    op.drop_table('room_admin_user_id')
    op.drop_table('live_record')
    op.drop_table('favorite_owner')
    op.drop_table('fans_group_admin_user_open_id')
    op.drop_table('fans_group_admin_user_id')
