##
## default download config
##
##>>------------------ base download config -------------------->>
save_path: /mnt/nvme2/vedio
log_path: ./logs
max_thread: 0
folderize: true
config_directory: "config"
stream_platform: "douyin"
build_directory: "build"
login: false
save_response: true
debug: false

##>>------------------ network download config -------------------->>
headers_file: "headers.yml"  # path = [stream_platform] + [headers_config_path]

##>>------------------ download config -------------------->>
download_file: "download.yml"