##<<--------------------- user login cofnig --------------------<<
login_config_file: login.yml

##<<------------------ download cofnig -------------<<
## post/live
type: live

##<<------------------ post download cofnig -------------<<
post_download_config_file: post.yml

##<<------------------ live download cofnig -------------<<
live_download_config_file: live.yml

##<<------------------ share link file -------------<<
multiple_download: true
share_url_file: conf.ini

##<<------------------ API -------------------------<<
api_file: api.yml