Accept: "*/*"
Accept-Language: 'zh-SG,zh-CN;q=0.9,zh;q=0.8'
Range: 'bytes=0-'
Referer: 'https://www.douyin.com/'
User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Saf
ari/537.36'
Content-Type: application/json; charset=utf-8