cookie: FOLLOW_LIVE_POINT_INFO=%22MS4wLjABAAAA4Md_rLi7sUqmSZV9C5-_ez2pu20RhErzFN6szJy8-TM%2F1712548800000%2F0%2F1712486487626%2F0%22;
  FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%7D; IsDouyinActive=true;
  LOGIN_STATUS=1; __security_server_data_status=1; _bd_ticket_crypt_cookie=8ca6a6fe3a9ce197c4ce8b4e754d72d3;
  _bd_ticket_crypt_doamin=2; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCQVVaYWp0OUZ3WE9RQytwcTlrY1RzaWhML3ZwVm1zNHExVlk3Q09nbUF2SDVlcURwU2FuTjB4VkRkVW5oZGdFbG1DclRqTHo5eXI4a2g3MGcxTERnbUE9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoxfQ%3D%3D;
  bd_ticket_guard_client_web_domain=2; download_guide=%220%2F%2F1%22; home_can_add_dy_2_desktop=%220%22;
  msToken=Nls7KJQiQJIXS11OMDJaeJ95kICughH2z3uUbqMbiQWKUjJlrJUf_QkMW7iwUiL1rUIuBO4jkLtLuDeY2exHi6818dmrVgLgXlHNwka7FXzXTYXDfU-Q;
  n_mh=ngQEn_iIBeY9pc84MWFmagRvS2A0XGdoFnmNVxQs35U; odin_tt=c15873a466ce9c014a598513e2bd1144adbdb8e52d3b61423d0d0443f3a1391a61746802e83bf44cae75e2ea6638c7c4f5b06b55ad27b0b9fabb4f0e7d234ef9;
  passport_assist_user=CjxucF5Q-2BCuWWMVhFixDRYbsSwDmyXwKsB4MDEOIe7GOm5mU_2iXnXx6lWBlU7kE6DGBC8VfUiFCep314aSgo835PopTQy5vu4mzUT6pe2dsSKI_U18lHfBMfG9SK_IuPOVYgFYwOIZfiSvsaoVnRhG3FhoY9wBcmfvCoDEIaCzg0Yia_WVCABIgEDI5R9UA%3D%3D;
  passport_auth_status=22ff69c04b77908489d73bc81c3e370c%2C; passport_auth_status_ss=22ff69c04b77908489d73bc81c3e370c%2C;
  passport_csrf_token=058d5b854ed17f403cbf0628bdf0c2ea; passport_csrf_token_default=058d5b854ed17f403cbf0628bdf0c2ea;
  publish_badge_show_info=%221%2C0%2C0%2C1712486487480%22; sessionid=75ab737d0860af5157013018a93a5ce9;
  sessionid_ss=75ab737d0860af5157013018a93a5ce9; sid_guard=75ab737d0860af5157013018a93a5ce9%7C1712486488%7C5183994%7CThu%2C+06-Jun-2024+10%3A41%3A22+GMT;
  sid_tt=75ab737d0860af5157013018a93a5ce9; sid_ucp_sso_v1=1.0.0-KDJjMzcwMTQ1YmY1NTAxODk5ZjRhYjQ1MmY3NGRhNGY2ZjJlYzlkYWEKHQjyvs7ghwIQz_DJsAYY7zEgDDD76rnOBTgGQPQHGgJsZiIgMTkwZmVhYjQzYzJmYzE5NmM3MDg3ZWE0MjY1ZTdjYTg;
  sid_ucp_v1=1.0.0-KDBmNzliYTY5MDc0ZmQ4MjViY2I0OWExNWFmNWJjNDBiN2JkNzg2MzQKGQjyvs7ghwIQ2PDJsAYY7zEgDDgGQPQHSAQaAmxmIiA3NWFiNzM3ZDA4NjBhZjUxNTcwMTMwMThhOTNhNWNlOQ;
  ssid_ucp_sso_v1=1.0.0-KDJjMzcwMTQ1YmY1NTAxODk5ZjRhYjQ1MmY3NGRhNGY2ZjJlYzlkYWEKHQjyvs7ghwIQz_DJsAYY7zEgDDD76rnOBTgGQPQHGgJsZiIgMTkwZmVhYjQzYzJmYzE5NmM3MDg3ZWE0MjY1ZTdjYTg;
  ssid_ucp_v1=1.0.0-KDBmNzliYTY5MDc0ZmQ4MjViY2I0OWExNWFmNWJjNDBiN2JkNzg2MzQKGQjyvs7ghwIQ2PDJsAYY7zEgDDgGQPQHSAQaAmxmIiA3NWFiNzM3ZDA4NjBhZjUxNTcwMTMwMThhOTNhNWNlOQ;
  sso_uid_tt=8e78eb455c711e65284607ee9d24f0e5; sso_uid_tt_ss=8e78eb455c711e65284607ee9d24f0e5;
  store-region=cn-sh; store-region-src=uid; strategyABtestKey=%221712486413.565%22;
  stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A0%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A1%7D%22;
  stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A16%2C%5C%22device_memory%5C%22%3A0%2C%5C%22downlink%5C%22%3A%5C%22%5C%22%2C%5C%22effective_type%5C%22%3A%5C%22%5C%22%2C%5C%22round_trip_time%5C%22%3A0%7D%22;
  toutiao_sso_user=190feab43c2fc196c7087ea4265e7ca8; toutiao_sso_user_ss=190feab43c2fc196c7087ea4265e7ca8;
  ttwid=1%7CuRB4ZT3e917sb1oFniTy_Qye8Y79-RhPulrpqwRJXZY%7C1712486408%7C707272f74f3a817ba6d72408eaaaeb63448dd5f7f302b68a4939f96910f7ebd0;
  uid_tt=29d18b02108cad7ba3c6ebcc3e1c45fe; uid_tt_ss=29d18b02108cad7ba3c6ebcc3e1c45fe;
  volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.5%7D;
  passport_fe_beating_status=true; =douyin.com; __ac_nonce=066127808008661a1851e;
  __ac_signature=_02B4Z6wo00f01eUJSOgAAIDBsaIh6X3NznHlOExAAB9S32; architecture=amd64;
  csrf_session_id=9750084836f0ee25f5dad83576c81dce; device_web_cpu_core=16; device_web_memory_size=-1;
  dy_sheight=1080; dy_swidth=1920; tt_scid=UmcfqyNrP07Fyrn9f8Rr9Z.yQkzBh2CBm00J-nO9ewyzoYknAk5-EktqRSUqslsS174a;
  ttcid=d6d75c350e8547c6bdfb6becf54760d228; xgplayer_user_id=779116200301
##
## for real msToken
##
msToken: cmDJA3i4FujBR1eEjQgL68DHy2zX0MPeN9tDhAr4NuCyG0dh_blLcIymp95LSmAre4HKR5MuoXvhWn0l_x0olXd26_Z6MA0bgJ_TCJLF0WN4nvfLpRF3733m3gxuhw==
# msToken: 5rNKkDfGkpKIZNkMb9D66UzslGTynlV8PkyJKfl3mXBTn--Z4GAxWQHSH0LfiVaXPUv0Ch6MDYsvULdNrvdAv3ewn4KLsIwEACvDWMwAE2fS4S3TAAJLNX4mzZFV-Q==
magic:
version:
dataType:
strData:
tspFromClient:
proxies: 
  http:
  https: