##
## for real msToken
##
msToken: cmDJA3i4FujBR1eEjQgL68DHy2zX0MPeN9tDhAr4NuCyG0dh_blLcIymp95LSmAre4HKR5MuoXvhWn0l_x0olXd26_Z6MA0bgJ_TCJLF0WN4nvfLpRF3733m3gxuhw==
# msToken: 5rNKkDfGkpKIZNkMb9D66UzslGTynlV8PkyJKfl3mXBTn--Z4GAxWQHSH0LfiVaXPUv0Ch6MDYsvULdNrvdAv3ewn4KLsIwEACvDWMwAE2fS4S3TAAJLNX4mzZFV-Q==
magic:
version:
dataType:
strData:
tspFromClient:
proxies: 
  http:
  https: