share_url: null
sec_user_id: "null"
nickname: "null"

device_platform: "webapp"
aid: "6383"
channel: "channel_pc_web"
pc_client_type: 1
version_code: "190500"
version_name: "19.5.0"
cookie_enabled: "true"
screen_width: 1920
screen_height: 1080
browser_language: "zh-CN"
browser_platform: "Win32"
browser_name: "Edge"
browser_version: "122.0.0.0"
browser_online: "true"
engine_name: "Blink"
engine_version: "122.0.0.0"
os_name: "Windows"
os_version: "10"
cpu_core_num: 12
device_memory: 8
platform: "PC"
downlink: 10
effective_type: "4g"
round_trip_time: 100
max_cursor: 0
page_counts: 20
max_counts: 0